name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install global dependencies
      run: |
        npm install -g tfx-cli typescript
      env:
        CI: true
    - name: npm install, build, and test
      working-directory: ./tasks/InsightAppSec
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - run: build package
      run: |
        tfx extension create --manifest-globs vss-extension.json
        
